// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tratoo.Domain.Data;

#nullable disable

namespace Tratoo.Domain.Migrations
{
    [DbContext(typeof(TratooContext))]
    [Migration("20260608025911_AdicionaCanceladoPorIdProjeto")]
    partial class AdicionaCanceladoPorIdProjeto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tratoo.Domain.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DataHora");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvaliadoId")
                        .HasColumnType("int");

                    b.Property<int>("AvaliadorId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ContratoServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.Property<byte?>("NotaComunicacao")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("NotaPrazo")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("NotaQualidade")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Publica")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublicadaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadoId");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("Status");

                    b.HasIndex("ContratoServicoId", "AvaliadorId")
                        .IsUnique();

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ConsentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConsentLogs");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ContratanteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiretrizesConteudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ExclusividadeSegmento")
                        .HasColumnType("bit");

                    b.Property<bool?>("ExigeAprovacaoPrevia")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MultaPorNaoEntrega")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("PermiteUsoImagem")
                        .HasColumnType("bit");

                    b.Property<string>("PlataformaPrincipal")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PrazoEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PrazoUsoImagemDias")
                        .HasColumnType("int");

                    b.Property<int?>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QuantidadePosts")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeReels")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeStories")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeVideos")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("ValorBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorMulta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("PlataformaPrincipal");

                    b.HasIndex("PrestadorId");

                    b.HasIndex("PropostaId")
                        .IsUnique()
                        .HasFilter("[PropostaId] IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ContratoServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssinadoContratanteEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AssinadoPrestadorEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CanceladoPorId")
                        .HasColumnType("int");

                    b.Property<string>("ConteudoHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConteudoJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContratanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("EntregaRegistradaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpPrestador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PdfKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TemplateVersao")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserAgentContratante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgentPrestador")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CanceladoPorId");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("PrestadorId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("PropostaId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("ContratosServico");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ContratoSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CongeladoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ConteudoFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DadosContratante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosPrestador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("ContratoSnapshots");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContratanteId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EncerradaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PrestadorId");

                    b.HasIndex("PropostaId");

                    b.ToTable("Conversas");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ConviteProjeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContratanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("MensagemInicial")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("OrcamentoSugerido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PrazoDesejado")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("Status");

                    b.HasIndex("PrestadorId", "ProjetoId");

                    b.ToTable("ConvitesProjeto");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AprovadaEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AprovadorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContratoServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoEntrega")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("RejeitadaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoServicoId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.EntregaAnexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChaveR2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("EntregaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("TamanhoArquivo")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EntregaId");

                    b.ToTable("EntregaAnexos");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.EntregaLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("EntregaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EntregaId");

                    b.ToTable("EntregaLinks");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Financeiro.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaCriptografada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("PixChave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPix")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId")
                        .IsUnique();

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Financeiro.DisputaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AbertoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("AbertoPorId")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciasJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotaResolucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResolvidaEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoId");

                    b.ToTable("DisputasPagamento");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Financeiro.LedgerFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoId");

                    b.ToTable("LedgerFinanceiro");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Financeiro.WebhookLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AsaasCobrancaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErroMensagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProcessadoComSucesso")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecebidoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AsaasCobrancaId");

                    b.HasIndex("ChaveIdempotencia")
                        .IsUnique();

                    b.ToTable("WebhookLogs");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.HistoricoAssinatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ContratoId", "UsuarioId");

                    b.ToTable("HistoricosAssinatura");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.HistoricoContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContratoServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContratoServicoId");

                    b.ToTable("HistoricosContrato");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnviadaEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.MensagemProjeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnviadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PropostaVersaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropostaVersaoId");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("PrestadorId", "EnviadoEm");

                    b.HasIndex("ProjetoId", "PrestadorId", "EnviadoEm");

                    b.ToTable("MensagensProjeto");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AsaasClienteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsaasTransferenciaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContratoServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstornadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayPagamentoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LiberacaoAutomaticaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LiberadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadGateway")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PixQrCodeExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PixQrCodeImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PixQrCodePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusGateway")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TaxaGateway")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ContratoServicoId");

                    b.HasIndex("GatewayPagamentoId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CertificacaoPrestador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstituicaoEmissora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkVerificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("CertificacoesPrestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CompetenciaCertificacao", b =>
                {
                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<int>("CertificacaoPrestadorId")
                        .HasColumnType("int");

                    b.HasKey("CompetenciaId", "CertificacaoPrestadorId");

                    b.HasIndex("CertificacaoPrestadorId");

                    b.ToTable("CompetenciaCertificacao");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CompetenciaExperiencia", b =>
                {
                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienciaPrestadorId")
                        .HasColumnType("int");

                    b.HasKey("CompetenciaId", "ExperienciaPrestadorId");

                    b.HasIndex("ExperienciaPrestadorId");

                    b.ToTable("CompetenciaExperiencia");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CompetenciaPortfolio", b =>
                {
                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioPrestadorId")
                        .HasColumnType("int");

                    b.HasKey("CompetenciaId", "PortfolioPrestadorId");

                    b.HasIndex("PortfolioPrestadorId");

                    b.ToTable("CompetenciaPortfolios");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.DisponibilidadeHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("DisponibilidadesHorario");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.ExperienciaPrestador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Atividades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmpregoAtual")
                        .HasColumnType("bit");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoContrato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("ExperienciasPrestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.PortfolioPrestador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("PortfoliosPrestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CanceladoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ContratanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FreelancerSelecionadoId")
                        .HasColumnType("int");

                    b.Property<string>("Habilidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelFreelancer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrcamentoMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrcamentoMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PrazoEntrega")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Publicado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPropostas")
                        .HasColumnType("int");

                    b.Property<string>("Visibilidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("FreelancerSelecionadoId");

                    b.HasIndex("Status");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Proposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CondicoesGerais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContratanteId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireitosUsoEntregavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireitosUsoImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuracaoMeses")
                        .HasColumnType("int");

                    b.Property<string>("Entregaveis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HorasEstimadas")
                        .HasColumnType("int");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoRecusa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrazoEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PrazoResposta")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondidaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoCobranca")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("PrestadorId");

                    b.ToTable("Propostas");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.PropostaNegociacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Autor")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrazoEntregaSugerido")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorSugerido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId");

                    b.ToTable("PropostaNegociacao");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.PropostaProjeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CanceladoPorId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ConviteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ValidoAte")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersaoAtual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConviteId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("Status");

                    b.HasIndex("PrestadorId", "ProjetoId");

                    b.ToTable("PropostasProjeto");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.PropostaVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CriadoPor")
                        .HasColumnType("int");

                    b.Property<decimal?>("Entrada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exclusoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarcosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrazoTotal")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisoesInclusas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId", "Versao")
                        .IsUnique();

                    b.ToTable("PropostaVersoes");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ReputacaoResumo", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Distribuicao1")
                        .HasColumnType("int");

                    b.Property<int>("Distribuicao2")
                        .HasColumnType("int");

                    b.Property<int>("Distribuicao3")
                        .HasColumnType("int");

                    b.Property<int>("Distribuicao4")
                        .HasColumnType("int");

                    b.Property<int>("Distribuicao5")
                        .HasColumnType("int");

                    b.Property<double>("MediaGeral")
                        .HasPrecision(4, 2)
                        .HasColumnType("float(4)");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId");

                    b.ToTable("ReputacaoResumos");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.UserIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoRepresentanteLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChavePixCriptografada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpfCnpjCriptografado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpfRepresentanteLegalCriptografado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("EmailRepresentanteLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExibirIdade")
                        .HasColumnType("bit");

                    b.Property<int>("NivelVerificacao")
                        .HasColumnType("int");

                    b.Property<string>("NomeLegal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeRepresentanteLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneRepresentanteLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserIdentities");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvaliacoesPrivado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IdentidadeVerificada")
                        .HasColumnType("bit");

                    b.Property<bool>("MFA")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PerfilMinimoCompleto")
                        .HasColumnType("bit");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoPessoa")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Contratante", b =>
                {
                    b.HasBaseType("Tratoo.Domain.Models.Usuario");

                    b.Property<DateOnly?>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Disponibilidade")
                        .HasColumnType("int");

                    b.Property<string>("EmailContato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExibirIdade")
                        .HasColumnType("bit");

                    b.Property<string>("IdiomasAceitosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PagadorVerificado")
                        .HasColumnType("bit");

                    b.Property<string>("PorQueTrabalharComigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segmento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TamanhoEquipe")
                        .HasColumnType("int");

                    b.ToTable("Contratantes", (string)null);
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.Prestador", b =>
                {
                    b.HasBaseType("Tratoo.Domain.Models.Usuario");

                    b.Property<bool?>("AceitaParcelamento")
                        .HasColumnType("bit");

                    b.Property<string>("AreaEspecializacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisponibilidadesPrivado")
                        .HasColumnType("bit");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DisponivelAPartirDe")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailContato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncaoExecutada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutrosLinks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PorcentagemCompleto")
                        .HasColumnType("int");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloProfissional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorMinimoProjeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Prestadores", (string)null);
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Avaliacao", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Usuario", "Avaliado")
                        .WithMany()
                        .HasForeignKey("AvaliadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Usuario", "Avaliador")
                        .WithMany()
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.ContratoServico", "ContratoServico")
                        .WithMany()
                        .HasForeignKey("ContratoServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Avaliado");

                    b.Navigation("Avaliador");

                    b.Navigation("ContratoServico");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Contrato", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Contratante", "Contratante")
                        .WithMany("Contratos")
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany("Contratos")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tratoo.Domain.Models.Proposta", "Proposta")
                        .WithOne()
                        .HasForeignKey("Tratoo.Domain.Models.Contrato", "PropostaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contratante");

                    b.Navigation("Prestador");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ContratoServico", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CanceladoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tratoo.Domain.Models.Contratante", "Contratante")
                        .WithMany()
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany()
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contratante");

                    b.Navigation("Prestador");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ContratoSnapshot", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.ContratoServico", "Contrato")
                        .WithOne("Snapshot")
                        .HasForeignKey("Tratoo.Domain.Models.ContratoSnapshot", "ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Conversa", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Contratante", "Contratante")
                        .WithMany()
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany()
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Proposta", "Proposta")
                        .WithMany()
                        .HasForeignKey("PropostaId");

                    b.Navigation("Contratante");

                    b.Navigation("Contrato");

                    b.Navigation("Prestador");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ConviteProjeto", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Contratante", "Contratante")
                        .WithMany()
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany()
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contratante");

                    b.Navigation("Prestador");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Entrega", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.ContratoServico", "ContratoServico")
                        .WithMany()
                        .HasForeignKey("ContratoServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContratoServico");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.EntregaAnexo", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Entrega", "Entrega")
                        .WithMany("Anexos")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.EntregaLink", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Entrega", "Entrega")
                        .WithMany("Links")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Financeiro.ContaBancaria", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithOne("ContaBancaria")
                        .HasForeignKey("Tratoo.Domain.Models.Financeiro.ContaBancaria", "PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Financeiro.DisputaPagamento", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Pagamento", "Pagamento")
                        .WithMany("Disputas")
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Financeiro.LedgerFinanceiro", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Pagamento", "Pagamento")
                        .WithMany("Ledger")
                        .HasForeignKey("PagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.HistoricoAssinatura", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.ContratoServico", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Mensagem", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Conversa", "Conversa")
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversa");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.MensagemProjeto", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.PropostaVersao", "PropostaVersao")
                        .WithMany()
                        .HasForeignKey("PropostaVersaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tratoo.Domain.Models.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("PropostaVersao");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Pagamento", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Contrato", "Contrato")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tratoo.Domain.Models.ContratoServico", "ContratoServico")
                        .WithMany()
                        .HasForeignKey("ContratoServicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contrato");

                    b.Navigation("ContratoServico");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CertificacaoPrestador", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany("Certificacoes")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.Competencia", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany("Competencias")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CompetenciaCertificacao", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.CertificacaoPrestador", "CertificacaoPrestador")
                        .WithMany("CompetenciaCertificacoes")
                        .HasForeignKey("CertificacaoPrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Prestador.Competencia", "Competencia")
                        .WithMany("CompetenciaCertificacoes")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificacaoPrestador");

                    b.Navigation("Competencia");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CompetenciaExperiencia", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.Competencia", "Competencia")
                        .WithMany("CompetenciaExperiencias")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Prestador.ExperienciaPrestador", "ExperienciaPrestador")
                        .WithMany("CompetenciaExperiencias")
                        .HasForeignKey("ExperienciaPrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competencia");

                    b.Navigation("ExperienciaPrestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CompetenciaPortfolio", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.Competencia", "Competencia")
                        .WithMany("CompetenciaPortfolios")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Prestador.PortfolioPrestador", "PortfolioPrestador")
                        .WithMany("CompetenciaPortfolios")
                        .HasForeignKey("PortfolioPrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competencia");

                    b.Navigation("PortfolioPrestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.DisponibilidadeHorario", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.ExperienciaPrestador", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany("Experiencias")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.PortfolioPrestador", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany("Portfolio")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Projeto", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Contratante", "Contratante")
                        .WithMany()
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "FreelancerSelecionado")
                        .WithMany()
                        .HasForeignKey("FreelancerSelecionadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contratante");

                    b.Navigation("FreelancerSelecionado");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Proposta", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Contratante", "Contratante")
                        .WithMany("PropostasEnviadas")
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany("PropostasRecebidas")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contratante");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.PropostaNegociacao", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Proposta", "Proposta")
                        .WithMany("Negociacoes")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.PropostaProjeto", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.ConviteProjeto", "Convite")
                        .WithMany()
                        .HasForeignKey("ConviteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tratoo.Domain.Models.Prestador.Prestador", "Prestador")
                        .WithMany()
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tratoo.Domain.Models.Projeto", "Projeto")
                        .WithMany("Propostas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convite");

                    b.Navigation("Prestador");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.PropostaVersao", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.PropostaProjeto", "Proposta")
                        .WithMany("Versoes")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ReputacaoResumo", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Tratoo.Domain.Models.ReputacaoResumo", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.UserIdentity", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Tratoo.Domain.Models.UserIdentity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Usuario", b =>
                {
                    b.OwnsOne("Tratoo.Domain.Models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Cep")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Cidade")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Complemento")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Estado")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Numero")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Contratante", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Tratoo.Domain.Models.Contratante", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.Prestador", b =>
                {
                    b.HasOne("Tratoo.Domain.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Tratoo.Domain.Models.Prestador.Prestador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Contrato", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.ContratoServico", b =>
                {
                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Entrega", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Pagamento", b =>
                {
                    b.Navigation("Disputas");

                    b.Navigation("Ledger");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.CertificacaoPrestador", b =>
                {
                    b.Navigation("CompetenciaCertificacoes");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.Competencia", b =>
                {
                    b.Navigation("CompetenciaCertificacoes");

                    b.Navigation("CompetenciaExperiencias");

                    b.Navigation("CompetenciaPortfolios");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.ExperienciaPrestador", b =>
                {
                    b.Navigation("CompetenciaExperiencias");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.PortfolioPrestador", b =>
                {
                    b.Navigation("CompetenciaPortfolios");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Projeto", b =>
                {
                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Proposta", b =>
                {
                    b.Navigation("Negociacoes");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.PropostaProjeto", b =>
                {
                    b.Navigation("Versoes");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Contratante", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("PropostasEnviadas");
                });

            modelBuilder.Entity("Tratoo.Domain.Models.Prestador.Prestador", b =>
                {
                    b.Navigation("Certificacoes");

                    b.Navigation("Competencias");

                    b.Navigation("ContaBancaria");

                    b.Navigation("Contratos");

                    b.Navigation("Disponibilidades");

                    b.Navigation("Experiencias");

                    b.Navigation("Portfolio");

                    b.Navigation("PropostasRecebidas");
                });
#pragma warning restore 612, 618
        }
    }
}
